@startuml 开发流程
|#pink|产品|
start

repeat :**用户反馈**;
#pink:**需求收集**;
#pink:**需求分析**;
#pink:**原型设计**;
|#lightgray|用户体验设计|
#lightgray:**交互设计**;
#lightgray:**视觉设计**;
|#lightblue|研发|
#lightblue:业务模型分析;
#lightblue:应用层分析;
#lightblue:技术选型;
#lightblue:架构设计;
#lightblue:编码;
#lightblue:测试;
repeat while (发布)

stop
@enduml
